# Generated by Django 3.0.6 on 2021-10-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_one_post_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
