# Generated by Django 3.0.6 on 2020-05-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0002_auto_20200529_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_comment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_follow',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
