# Generated by Django 3.0.6 on 2020-05-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0003_auto_20200529_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
