# Generated by Django 3.0.6 on 2020-05-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0004_auto_20200529_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
    ]
