# Generated by Django 3.0.6 on 2020-06-03 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testy', '0007_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, upload_to='images/')),
                ('is_photo', models.BooleanField(blank=True, default=False)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=19)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.RemoveField(
            model_name='usermedia',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
        migrations.DeleteModel(
            name='UserMedia',
        ),
        migrations.AddField(
            model_name='comments',
            name='nature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testy.Nature'),
        ),
    ]
