# Generated by Django 3.0.6 on 2020-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0008_auto_20200603_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nature',
            name='photo',
            field=models.FileField(upload_to='images/'),
        ),
    ]
