# Generated by Django 3.0.6 on 2020-06-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0009_auto_20200603_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nature',
            name='is_photo',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='photo',
        ),
        migrations.CreateModel(
            name='NatureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('is_photo', models.BooleanField(blank=True, default=False)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='testy.Nature')),
            ],
        ),
    ]
