# Generated by Django 3.0.6 on 2020-06-20 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testy', '0014_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='nature',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nature',
            name='hide_post',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='nature',
            name='restrict_comment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
