# Generated by Django 3.0.6 on 2020-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0015_auto_20200620_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_follow_request',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
